"""empty message

Revision ID: 049a6e50272c
Revises: 7b4c3d9ce418
Create Date: 2021-07-07 19:55:03.675843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049a6e50272c'
down_revision = '7b4c3d9ce418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist_image_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'artist_image_link')
    # ### end Alembic commands ###
