"""empty message

Revision ID: 937324b99d61
Revises: f1976c22c9f5
Create Date: 2021-07-07 20:38:53.475122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937324b99d61'
down_revision = 'f1976c22c9f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=30), nullable=True),
    sa.Column('artist_image_link', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show')
    # ### end Alembic commands ###
