"""empty message

Revision ID: da69f7db3f7b
Revises: 9b0b9356520e
Create Date: 2021-07-02 16:08:21.104303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da69f7db3f7b'
down_revision = '9b0b9356520e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=250), nullable=True))
    op.add_column('Artist', sa.Column('venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'description')
    op.drop_column('Artist', 'Venue')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
